/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;


import java.util.Map;
import negocio.ProductoNegocio;
/**
 *
 * @author Crisly
 */
public class EstadisticasPanel extends javax.swing.JPanel {
    private ProductoNegocio productoNegocio;

    /**
     * Creates new form EstadisticasPanel
     */


public EstadisticasPanel() {

    initComponents();

    productoNegocio = new ProductoNegocio();

    actualizarEstadisticas();


}

private void actualizarEstadisticas() {

    lblTotalProductos.setText(
            String.valueOf(productoNegocio.totalProductos()));

    lblDisponibles.setText(
            String.valueOf(productoNegocio.productosDisponibles()));

    lblValorInventario.setText(
            String.format("%.2f",
                    productoNegocio.valorInventario()));

    Map<String, Integer> mapa =
            productoNegocio.productosPorCategoria();

    StringBuilder texto = new StringBuilder("<html>");

    for (String categoria : mapa.keySet()) {

        texto.append(categoria)
             .append(": ")
             .append(mapa.get(categoria))
             .append("<br>");

    }

    texto.append("</html>");

    lblCategorias.setText(texto.toString());

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalProductos = new javax.swing.JLabel();
        lblDisponibles = new javax.swing.JLabel();
        lblValorInventario = new javax.swing.JLabel();
        lblCategorias = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        lblTotalProductos.setText("0");

        lblDisponibles.setText("0");

        lblValorInventario.setText("0.00");

        lblCategorias.setText("--");

        btnActualizar.setText("Actualizar inventario");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        jLabel1.setText("Productos por categoría");

        jLabel2.setText("Valor total del inventario:");

        jLabel3.setText("Productos disponibles:");

        jLabel4.setText("Total de productos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisponibles)
                    .addComponent(lblValorInventario)
                    .addComponent(lblCategorias)
                    .addComponent(btnActualizar)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblTotalProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(lblTotalProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCategorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
         actualizarEstadisticas();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblDisponibles;
    private javax.swing.JLabel lblTotalProductos;
    private javax.swing.JLabel lblValorInventario;
    // End of variables declaration//GEN-END:variables
}
