/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import negocio.ProductoNegocio;
import java.util.List;
/**
 *
 * @author Crisly
 */
public class ListaProductosPanel extends javax.swing.JPanel {
private ProductoNegocio productoNegocio;
    /**
     * Creates new form ListaProductosPanel
     */
    public ListaProductosPanel() {
    initComponents();

    productoNegocio = new ProductoNegocio();

    cargarTabla();
}
    
    private void cargarTabla() {

    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Código");
    modelo.addColumn("Nombre");
    modelo.addColumn("Categoría");
    modelo.addColumn("Cantidad");
    modelo.addColumn("Precio");
    modelo.addColumn("Disponible");

    List<Producto> lista = productoNegocio.listar();

    for (Producto p : lista) {

        modelo.addRow(new Object[]{
            p.getCodigo(),
            p.getNombre(),
            p.getCategoria(),
            p.getCantidad(),
            p.getPrecio(),
            p.isDisponible()
        });

    }

    TablaProductos.setModel(modelo);

}
    
    
    private void cargarTabla(List<Producto> lista) {

    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Código");
    modelo.addColumn("Nombre");
    modelo.addColumn("Categoría");
    modelo.addColumn("Cantidad");
    modelo.addColumn("Precio");
    modelo.addColumn("Disponible");

    for (Producto p : lista) {

        modelo.addRow(new Object[]{
            p.getCodigo(),
            p.getNombre(),
            p.getCategoria(),
            p.getCantidad(),
            p.getPrecio(),
            p.isDisponible()
        });

    }

    TablaProductos.setModel(modelo);

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProductos);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnEliminar.setText("Eliminar producto");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnOrdenar.setText("Ordenar A-Z");
        btnOrdenar.addActionListener(this::btnOrdenarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrdenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnOrdenar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = TablaProductos.getSelectedRow();

if (fila == -1) {

    javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione un producto.");

    return;
}

String codigo = TablaProductos.getValueAt(fila, 0).toString();

int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Eliminar este producto?",
        "Confirmar",
        javax.swing.JOptionPane.YES_NO_OPTION);

if (opcion == javax.swing.JOptionPane.YES_OPTION) {

    productoNegocio.eliminar(codigo);

    cargarTabla();

}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      String texto = txtBuscar.getText();

    List<Producto> lista = productoNegocio.buscar(texto);

    cargarTabla(lista);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        productoNegocio.ordenarPorNombre();

    cargarTabla();
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = TablaProductos.getSelectedRow();

    if (fila == -1) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un producto.");

        return;
    }

    String codigo = TablaProductos.getValueAt(fila, 0).toString();

    Producto producto = productoNegocio.buscarPorCodigo(codigo);

    if (producto == null) {
    return;
}

try {

    String nombre = javax.swing.JOptionPane.showInputDialog(
            this,
            "Nuevo nombre:",
            producto.getNombre());

    String categoria = javax.swing.JOptionPane.showInputDialog(
            this,
            "Nueva categoría:",
            producto.getCategoria());

    int cantidad = Integer.parseInt(
            javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Nueva cantidad:",
                    producto.getCantidad()));

    double precio = Double.parseDouble(
            javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Nuevo precio:",
                    producto.getPrecio()));

    producto.setNombre(nombre);
    producto.setCategoria(categoria);
    producto.setCantidad(cantidad);
    producto.setPrecio(precio);

    productoNegocio.actualizar(producto);

    cargarTabla();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Producto actualizado correctamente.");

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            e.getMessage());

}
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
